# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: ${WWWGROUP}
        image: sail-8.0/app
        container_name: app

        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: ${WWWUSER}
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysqlServerLaravel
            # - pgsql
            - redis
            # - selenium
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    mysqlServerLaravel:
        image: mysql:latest
        container_name: mysqlServerLaravel
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]

    # Check availble environment variables here: https://github.com/wodby/adminer
    # adminer:
    #   image: adminer
    #   container_name: adminer
    #   restart: always
    #   ports:
    #     - ${ADMINER_PORT:-8080}:8080
    #   environment: 
    #     ADMINER_DEFAULT_DB_HOST: mysql
    #     ADMINER_DEFAULT_DB_DRIVER: mysql
    #     ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
    #     ADMINER_DESIGN: nette ##galkaev
    #     ADMINER_PLUGINS: tables-filter tinymce
    
    #   depends_on:
    #      - mysql
    #   networks:
    #      - sail

    # Check availble environment variables here: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pmaLaravel
        environment:
          PMA_HOST: mysqlServerLaravel
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        #   PMA_USER: root
        #   PMA_PASSWORD: ${DB_ROOT_PASSWORD}
        restart: always
        ports:
          - ${PHPMYADMIN_PORT:-8081}:80
        # depends_on:
        #   - mysql
        links:
          - mysqlServerLaravel
        networks:
          - sail

    redis:
        image: 'redis:alpine'
        container_name: redis

        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog

        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
#    sailpostgresql:
#        driver: local
    sailredis:
        driver: local
